export const CREATE_NEW_MESSAGE_REQUEST = "CREATE_NEW_MESSAGE_REQUEST";
export const CREATE_NEW_MESSAGE_SUCCESS = "CREATE_NEW_MESSAGE_SUCCESS";
export const CREATE_NEW_MESSAGE_FAILURE = "CREATE_NEW_MESSAGE_FAILURE";

export const GET_ALL_MESSAGES_REQUEST = "GET_ALL_MESSAGES_REQUEST";
export const GET_ALL_MESSAGES_SUCCESS = "GET_ALL_MESSAGES_SUCCESS";
export const GET_ALL_MESSAGES_FAILURE = "GET_ALL_MESSAGES_FAILURE";

export const DELETE_MESSAGE_REQUEST = "DELETE_MESSAGE_REQUEST";
export const DELETE_MESSAGE_SUCCESS = "DELETE_MESSAGE_SUCCESS";
export const DELETE_MESSAGE_FAILURE = "DELETE_MESSAGE_FAILURE";

export const CLEAR_MESSAGE_ERROR = "CLEAR_MESSAGE_ERROR";
