export const CREATE_CHAT_REQUEST = "CREATE_CHAT_REQUEST";
export const CREATE_CHAT_SUCCESS = "CREATE_CHAT_SUCCESS";
export const CREATE_CHAT_FAILURE = "CREATE_CHAT_FAILURE";

export const CREATE_GROUP_REQUEST = "CREATE_GROUP_REQUEST";
export const CREATE_GROUP_SUCCESS = "CREATE_GROUP_SUCCESS";
export const CREATE_GROUP_FAILURE = "CREATE_GROUP_FAILURE";

export const GET_USERS_CHAT_REQUEST = "GET_USERS_CHAT_REQUEST";
export const GET_USERS_CHAT_SUCCESS = "GET_USERS_CHAT_SUCCESS";
export const GET_USERS_CHAT_FAILURE = "GET_USERS_CHAT_FAILURE";

export const DELETE_CHAT_REQUEST = "DELETE_CHAT_REQUEST";
export const DELETE_CHAT_SUCCESS = "DELETE_CHAT_SUCCESS";
export const DELETE_CHAT_FAILURE = "DELETE_CHAT_FAILURE";

export const CLEAR_CHAT_ERROR = "CLEAR_CHAT_ERROR";
